version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - bodyclose
    - noctx
    - stylecheck
    - gosec
    - unconvert
    - goconst
    - asciicheck
    - goheader
    - lll
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - gocritic
    - whitespace
    - goprintffuncname
    - testpackage
    - nestif
    - sqlclosecheck
    - gocyclo
    - funlen
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - bin
      - hack
      - test
      - vendor
      - third_party
      - ".*generate\\.go$"

  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - unnecessaryDefer
        - appendAssign
        - importShadow
        - sloppyReassign
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    lll:
      line-length: 140
    gocyclo:
      min-complexity: 10
    funlen:
      lines: 100
      statements: 70

formatters:
  enable:
    - gofmt
    - goimports