apiVersion: postgresql-operator.vyrodovalexey.github.com/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  database: "testdb"
  owner: "testuser"
  schema: "testschema"
  postgresqlID: "test-pg-001"
