---
apiVersion: postgresql-operator.vyrodovalexey.github.com/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-sample-reader
spec:
  username: "testreader"
  updatePassword: false
  postgresqlID: "test-pg-001"

---
apiVersion: postgresql-operator.vyrodovalexey.github.com/v1alpha1
kind: Grant
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: grant-sample
spec:
  role: "testreader"
  database: "testdb"
  postgresqlID: "test-pg-001"

  grants:
    # Grant CONNECT privilege on the database
    - type: database
      privileges: [CONNECT]

    # Grant USAGE privilege on the public schema
    - type: schema
      schema: public
      privileges: [USAGE]

    # Grant SELECT privilege on all existing tables in the public schema
    - type: all_tables
      schema: public
      privileges: [SELECT]

    # Grant SELECT and USAGE privileges on all existing sequences in the public schema
    - type: all_sequences
      schema: public
      privileges: [SELECT, USAGE]

  defaultPrivileges:
    # Grant SELECT privilege on future tables in the public schema
    - objectType: tables
      schema: public
      privileges: [SELECT]

    # Grant SELECT and USAGE privileges on future sequences in the public schema
    - objectType: sequences
      schema: public
      privileges: [SELECT, USAGE]
