apiVersion: postgresql-operator.vyrodovalexey.github.com/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: schema-sample
spec:
  schema: "testschema"
  database: "testdb"
  owner: "testuser"
  postgresqlID: "test-pg-001"
