apiVersion: postgresql-operator.vyrodovalexey.github.com/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  username: "testuser"
  updatePassword: false
  postgresqlID: "test-pg-001"
