apiVersion: postgresql-operator.vyrodovalexey.github.com/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  # Username is the PostgreSQL username to create
  username: "myuser"
  
  # Regenerate password
  updatePassword: false
  
  # PostgresqlID is the ID of the PostgreSQL instance where this user should be created
  # This must match the postgresqlID in the Postgresql CRD
  # Password will be stored in Vault at: secret/pdb/test-pg-001/myuser
  postgresqlID: "test-pg-001"

